Remove Simple Steam Auth plugin entry
Removed Simple Steam Auth plugin entry from the list to avoid this error

Run actions/github-script@v6
Repo info: dreamscached/obsidian-simple-steam-auth
Found issue: The newly added entry is not at the end, or you are submitting on someone else's behalf. The last plugin in the list is: `dreamscached/obsidian-simple-steam-auth`. If you are submitting from a GitHub org, you need to be a public member of the org.
Error: Failed to validate plugin